### ISSUE TITLE
Cpp compilation issue

### ISSUE THREAD

**Issue by eliasku** [snowkit/linc_opengl#3]
Seems like `linc_opengl.cpp:294` line:

```
Array< ::Int > result = Array_obj< ::Int >::__new();
```

should be fixed to:

```
::Array<int> result = ::Array_obj<int>::__new();
```

Thanks

**Comment by ruby0x1** [comment]
Can you give more information about your compiler + platform? I'm curious, but the fix is in :)

**Comment by eliasku** [comment]
osx 10.11.5, the latest hxcpp, the latest haxe 3.3 nightly.
I think it's because of updated hxcpp library

BTW, thanks for the fix!
